### ISSUE TITLE
Release checklist for v1.65.1 (scheduled)

### ISSUE THREAD

**Issue by jhnstn** [jhnstn/release-toolkit-gutenberg-mobile#1]
### Pre release

- [ ] Review [Release process notes](#)
- [ ] [Notifiy open Gutenberg Mobile PRs assigned to 1.65.1 milestone](#) ([message template](#)).
- [ ] Create WPiOS and WPAndroid builds from `develop` and complete the [general writing flow tests](https://href.li/?https://github.com/wordpress-mobile/test-cases/tree/master/test-cases/gutenberg/writing-flow).
- [ ] Clone or update the [release toolkit](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile) and review the [release script instructions](https://href.li/?https://github.com/wordpress-mobile/release-toolkit-gutenberg-mobile/blob/develop/Releasing.md).

### Create the Release

- [ ] [Verify Aztec is up to date](#).
- [ ] Run `./release_automation.sh`from the release toolkit to generate the main apps integration PRs [\*](#).
- [ ] [Notify team that the release has been cut.](#) ([message template](#))
- [ ] [Verify localization string files have been generated properly](#).
- [ ] [Update `Unreleased`](#) section in [`RELEASE-NOTES.txt`](#) and [`gutenberg/../CHANGELOG.md`](#)
- [ ] [Perform quick smoke test of the editor on both iOS and Android builds.](#)
- [ ] Update [Gutenberg Mobile PR](#) description. Make sure the "Changes" section [informs testers on what is in the release.](#)
- [ ] Mark all 4 PRs ready for review.

### Integrate the Release

- [ ] Verify `gutenberg` ref within the gutenberg-mobile release branch is pointing to the [latest commit](#) in Gutenberg release branch.
- [ ] Create and push a `rnmobile/1.65.1` git tag for the head of [Gutenberg release branch](https://github.com/WordPress/gutenberg/branches/all?query=rnmobile%2Frelease).
- [ ] [Update bundles in the Gutenberg Mobile release branch](#).
- [ ] Merge **gutenberg-mobile** PR to `trunk` [using the "Create a merge commit" option](#). **WARNING** do **not** merge gutenberg PR to `trunk` yet.
- [ ] [Create a new Gutenberg moble release](#).
- [ ] [Update Gutenberg mobile references in the main apps](#).
- [ ] Re-run optional tests on main apps PRs.
- [ ] Merge main apps PSs to the respective `develop` branches.
- [ ] Notify team that the release is now in the main apps `develop` branches ([mesage template](#))

### Sync Release

- [ ] Merge Guteberg release PR to `gutenberg/trunk`.
- [ ] [Merge release changes back to `gutenberg-mobile/develop`](#) e.g. `trunk -> merge_release_1.65.1_to_develop -> develop`
